import type { DemoState } from "@/lib/types";

const futureDate = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

export const initialState: DemoState = {
  activeUserId: null,
  users: [
    {
      id: "user-brand",
      displayName: "Orbit Labs",
      handle: "@orbitlabs",
      avatar: "OL",
      walletAddress: "0x71C2d35Ec8AE08b4a39Ea56Cd62A1Fb58E89A120",
      role: "brand",
      bio: "Building delightful consumer crypto products.",
    },
    {
      id: "user-clipper",
      displayName: "Naya Cuts",
      handle: "@nayacuts",
      avatar: "NC",
      walletAddress: "0x8BE1a789B06C5FBB123241D0A60160F348c72591",
      role: "clipper",
      bio: "Short-form editor. Fast cuts, strong hooks, internet native.",
    },
    {
      id: "user-admin",
      displayName: "Clipfun Ops",
      handle: "@clipfun",
      avatar: "CF",
      walletAddress: "0x22B62314Ba82e3F6703BA035Fe1A951D238059d1",
      role: "admin",
      bio: "Marketplace operations and moderation.",
    },
  ],
  socialProfiles: [
    {
      id: "social-1",
      userId: "user-clipper",
      provider: "tiktok",
      username: "@nayacuts",
      profileUrl: "https://tiktok.com/@nayacuts",
      verified: true,
    },
    {
      id: "social-2",
      userId: "user-clipper",
      provider: "youtube",
      username: "@nayacuts",
      profileUrl: "https://youtube.com/@nayacuts",
      verified: true,
    },
  ],
  campaigns: [
    {
      id: "camp-orbit",
      brandId: "user-brand",
      brandName: "Orbit Labs",
      brandAvatar: "OL",
      title: "Make crypto feel human",
      summary:
        "Turn our wallet launch into a 20–35 second story people actually want to watch.",
      brief:
        "Show how Orbit removes the awkward parts of onboarding into crypto. The video should feel creator-native, not like a traditional ad. Start with a relatable frustration, reveal Orbit as the fix, and end with one clear call to action.",
      requirements: [
        "Vertical 9:16 video, 20–35 seconds",
        "Show the Orbit app UI for at least 3 seconds",
        "Include campaign code CF-82KD in the caption",
        "Use original voiceover or on-camera delivery",
      ],
      prohibited: [
        "Financial return promises",
        "Reused or watermarked content",
        "Competitor logos",
      ],
      category: "Web3",
      platform: "all",
      rewardPerSubmission: 50,
      maxWinners: 10,
      paidWinners: 3,
      submissionCount: 18,
      deadline: futureDate(9),
      status: "OPEN",
      campaignCode: "CF-82KD",
      visual: "blue",
      createdAt: futureDate(-8),
      fundingTxHash:
        "0x4ab5e8e30d7720fbbbe1c4ad6ac2209b953169cfe515267263fb77184955d0a9",
    },
    {
      id: "camp-zest",
      brandId: "brand-zest",
      brandName: "Zest Soda",
      brandAvatar: "ZS",
      title: "Sip loud. Live louder.",
      summary:
        "Create a high-energy product moment for our new yuzu soda drop.",
      brief:
        "Make the first sip feel like a plot twist. We want bright environments, expressive reactions, and fast cuts.",
      requirements: [
        "Vertical video under 30 seconds",
        "Product visible in first 5 seconds",
        "Include #ZestMode and campaign code",
      ],
      prohibited: ["Alcohol references", "Unsafe stunts"],
      category: "Food & Drink",
      platform: "tiktok",
      rewardPerSubmission: 35,
      maxWinners: 20,
      paidWinners: 7,
      submissionCount: 34,
      deadline: futureDate(5),
      status: "OPEN",
      campaignCode: "CF-ZEST",
      visual: "orange",
      createdAt: futureDate(-13),
    },
    {
      id: "camp-pixel",
      brandId: "brand-pixel",
      brandName: "Pixel Forge",
      brandAvatar: "PF",
      title: "Your setup, remixed",
      summary:
        "Give your desk setup a before-and-after transformation with Pixel Forge.",
      brief:
        "Show a relatable messy setup and transform it with our accessories. Lean into satisfying transitions.",
      requirements: [
        "Before and after sequence",
        "Tag @pixelforge",
        "Show at least two products",
      ],
      prohibited: ["Misleading discounts"],
      category: "Gaming",
      platform: "instagram",
      rewardPerSubmission: 75,
      maxWinners: 8,
      paidWinners: 2,
      submissionCount: 11,
      deadline: futureDate(14),
      status: "OPEN",
      campaignCode: "CF-PX31",
      visual: "purple",
      createdAt: futureDate(-5),
    },
    {
      id: "camp-bloom",
      brandId: "brand-bloom",
      brandName: "Bloom",
      brandAvatar: "BL",
      title: "Touch grass challenge",
      summary:
        "A playful reminder to take a real break with Bloom’s focus timer.",
      brief:
        "Turn screen-time guilt into a positive, funny outdoor moment.",
      requirements: ["Use the in-app timer", "Outdoor final shot"],
      prohibited: ["Mental health claims"],
      category: "Lifestyle",
      platform: "youtube",
      rewardPerSubmission: 25,
      maxWinners: 25,
      paidWinners: 10,
      submissionCount: 41,
      deadline: futureDate(3),
      status: "OPEN",
      campaignCode: "CF-GRASS",
      visual: "lime",
      createdAt: futureDate(-18),
    },
  ],
  submissions: [
    {
      id: "sub-claimable",
      campaignId: "camp-orbit",
      campaignTitle: "Make crypto feel human",
      clipperId: "user-clipper",
      clipperName: "Naya Cuts",
      clipperAvatar: "NC",
      platform: "tiktok",
      postUrl: "https://tiktok.com/@nayacuts/video/741838291",
      status: "CLAIMABLE",
      submittedAt: futureDate(-2),
      payoutId: "payout-1",
    },
    {
      id: "sub-review",
      campaignId: "camp-zest",
      campaignTitle: "Sip loud. Live louder.",
      clipperId: "user-clipper",
      clipperName: "Naya Cuts",
      clipperAvatar: "NC",
      platform: "tiktok",
      postUrl: "https://tiktok.com/@nayacuts/video/741838400",
      status: "UNDER_REVIEW",
      submittedAt: futureDate(-1),
    },
    {
      id: "sub-admin-1",
      campaignId: "camp-pixel",
      campaignTitle: "Your setup, remixed",
      clipperId: "creator-lino",
      clipperName: "Lino Frames",
      clipperAvatar: "LF",
      platform: "instagram",
      postUrl: "https://instagram.com/reel/demo-pixel-forge",
      status: "UNDER_REVIEW",
      submittedAt: futureDate(-1),
    },
  ],
  payouts: [
    {
      id: "payout-1",
      submissionId: "sub-claimable",
      walletAddress: "0x8BE1a789B06C5FBB123241D0A60160F348c72591",
      rewardAmount: 50,
      feeAmount: 2.5,
      nonce: 184,
      expiry: futureDate(3),
      signature: "0xdemo_eip712_signature_82kd",
      status: "ISSUED",
    },
  ],
  transactions: [
    {
      id: "tx-fund-orbit",
      type: "FUND",
      campaignId: "camp-orbit",
      campaignTitle: "Make crypto feel human",
      amount: 525,
      status: "CONFIRMED",
      hash: "0x4ab5e8e30d7720fbbbe1c4ad6ac2209b953169cfe515267263fb77184955d0a9",
      createdAt: futureDate(-7),
    },
  ],
};
